on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    environment: 
      name:  default
    name: Deploy to Cloudflare Workers
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Run your project's build step
      - name: Build
        run: npm install && npm run build
      - name: Deploy
        uses: cloudflare/wrangler-action
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
